#ifndef TPE_ERROR_CODES_H
#define TPE_ERROR_CODES_H

#define INTEGER_OUT_OF_RANGE     0
#define FLOAT_OUT_OF_RANGE       1
#define INVALID_RESERVED_WORD    2
#define UNEXPECTED_CHARACTER     3
#define INTEGER_WITHOUT_SUFFIX   4
#define EXPONENT_WITHOUT_SIGN    5
#define FLOAT_WITHOUT_NUMBERS    6
#define STRING_LITERAL_WITH_ENDL 7
#define UNCLOSED_STRING_LITERAL  8
#define UNOPENED_COMMENT         9
#define UNCLOSED_COMMENT         10
#define INVALID_COLON            11


#define SYNTAX_ERROR             12

/*    For Warnings    */

#define TRUNCATED_VARIABLE 0

#endif //TPE_ERROR_CODES_H